%% Create a combined file with all ocean CTD data
% FANS Greenland - ARICE 2025
% RBR concerto3 (16Hz)
% VERSION 5: with QC flags, soak info, validation and qc_summary
% Nina Hoareau, Jan. 2025

clear all
close all

%% Load station files
disp('Loading station files...')
fans_path = '../outputs/';

% Stations 16Hz
d1A = load([fans_path 'PROC_CTD_FANS_1A.mat']);
d1B = load([fans_path 'PROC_CTD_FANS_1B.mat']);
d2C = load([fans_path 'PROC_CTD_FANS_2C.mat']);
d3D = load([fans_path 'PROC_CTD_FANS_3D.mat']);
d4E = load([fans_path 'PROC_CTD_FANS_4E.mat']);
d5F = load([fans_path 'PROC_CTD_FANS_5F.mat']);
d6G = load([fans_path 'PROC_CTD_FANS_6G.mat']);
d7H = load([fans_path 'PROC_CTD_FANS_7H.mat']);
d7I = load([fans_path 'PROC_CTD_FANS_7I.mat']);
d8J = load([fans_path 'PROC_CTD_FANS_8J.mat']);

% Station summary (fixed names, counts from loaded data)
stn_summary = struct( ...
    'name', {'1A',              '1B',              '2C',              '3D',              '4E', ...
             '5F',              '6G',              '7H',              '7I',              '8J', ...
             }, ...
    'n',    {length(d1A.ctdid), length(d1B.ctdid), length(d2C.ctdid), length(d3D.ctdid), length(d4E.ctdid), ...
             length(d5F.ctdid), length(d6G.ctdid), length(d7H.ctdid), length(d7I.ctdid), length(d8J.ctdid), ...
             });

%% Concatenate atmospheric variables
atmhPa1 = [d1A.atmhPa1 d1B.atmhPa1 d2C.atmhPa1 d3D.atmhPa1 ...
    d4E.atmhPa1 d5F.atmhPa1 d6G.atmhPa1 d7H.atmhPa1 d7I.atmhPa1 d8J.atmhPa1 ...
    ];
atmhPa2 = [d1A.atmhPa2 d1B.atmhPa2 d2C.atmhPa2 d3D.atmhPa2 ...
    d4E.atmhPa2 d5F.atmhPa2 d6G.atmhPa2 d7H.atmhPa2 d7I.atmhPa2 d8J.atmhPa2 ...
    ];
atmrelativehumidity = [d1A.atmrelativehumidity d1B.atmrelativehumidity d2C.atmrelativehumidity ...
    d3D.atmrelativehumidity d4E.atmrelativehumidity ...
    d5F.atmrelativehumidity d6G.atmrelativehumidity d7H.atmrelativehumidity ...
    d7I.atmrelativehumidity d8J.atmrelativehumidity ];
atmwinddirection = [d1A.atmwinddirection d1B.atmwinddirection d2C.atmwinddirection ...
    d3D.atmwinddirection d4E.atmwinddirection ...
    d5F.atmwinddirection d6G.atmwinddirection d7H.atmwinddirection ...
    d7I.atmwinddirection d8J.atmwinddirection ];
atmwindspeed = [d1A.atmwindspeed d1B.atmwindspeed d2C.atmwindspeed ...
    d3D.atmwindspeed d4E.atmwindspeed ...
    d5F.atmwindspeed d6G.atmwindspeed d7H.atmwindspeed ...
    d7I.atmwindspeed d8J.atmwindspeed ];

%% Concatenate metadata
ctdid = [d1A.ctdid d1B.ctdid d2C.ctdid d3D.ctdid ...
    d4E.ctdid d5F.ctdid d6G.ctdid d7H.ctdid d7I.ctdid d8J.ctdid ...
    ];
% ctddate may be row or column vector depending on the file — force row
ctddate = [d1A.ctddate(:)' d1B.ctddate(:)' d2C.ctddate(:)' d3D.ctddate(:)' ...
    d4E.ctddate(:)' d5F.ctddate(:)' d6G.ctddate(:)' d7H.ctddate(:)' d7I.ctddate(:)' d8J.ctddate(:)' ...
    ];
ctdlat = [d1A.ctdlat(:)' d1B.ctdlat(:)' d2C.ctdlat(:)' d3D.ctdlat(:)' ...
    d4E.ctdlat(:)' d5F.ctdlat(:)' d6G.ctdlat(:)' d7H.ctdlat(:)' d7I.ctdlat(:)' d8J.ctdlat(:)' ...
    ];
ctdlon = [d1A.ctdlon(:)' d1B.ctdlon(:)' d2C.ctdlon(:)' d3D.ctdlon(:)' ...
    d4E.ctdlon(:)' d5F.ctdlon(:)' d6G.ctdlon(:)' d7H.ctdlon(:)' d7I.ctdlon(:)' d8J.ctdlon(:)' ...
    ];

%% NaN-padding — align all stations to obs_max rows
% Required at native resolution (do_binning=false): each station has a
% different number of rows. In binned mode (600 rows), obs_max=600
% and the padding has no effect.
all_stations = {d1A, d1B, d2C, d3D, d4E, d5F, d6G, d7H, d7I, d8J};
obs_max = max(cellfun(@(d) size(d.ctdtemp, 1), all_stations));
fprintf('  obs_max (rows): %d\n', obs_max);

pad = @(M) [M; NaN(obs_max - size(M,1), size(M,2))];  % NaN-pad to obs_max rows
pad_qc = @(M) [M; 9*ones(obs_max - size(M,1), size(M,2), 'int8')];  % QC pad = 9 (Missing)

%% Concatenate CTD data
ctdseapres = [pad(d1A.ctdseapres) pad(d1B.ctdseapres) pad(d2C.ctdseapres) pad(d3D.ctdseapres) ...
    pad(d4E.ctdseapres) pad(d5F.ctdseapres) pad(d6G.ctdseapres) pad(d7H.ctdseapres) ...
    pad(d7I.ctdseapres) pad(d8J.ctdseapres)];

ctdsampltime = [pad(d1A.ctdsampltime) pad(d1B.ctdsampltime) pad(d2C.ctdsampltime) pad(d3D.ctdsampltime) ...
    pad(d4E.ctdsampltime) pad(d5F.ctdsampltime) pad(d6G.ctdsampltime) pad(d7H.ctdsampltime) ...
    pad(d7I.ctdsampltime) pad(d8J.ctdsampltime)];

ctddepth = [pad(d1A.ctddepth) pad(d1B.ctddepth) pad(d2C.ctddepth) pad(d3D.ctddepth) ...
    pad(d4E.ctddepth) pad(d5F.ctddepth) pad(d6G.ctddepth) pad(d7H.ctddepth) ...
    pad(d7I.ctddepth) pad(d8J.ctddepth)];
ctddepth_mean = mean(ctddepth, 2, 'omitnan');

ctdcond = [pad(d1A.ctdcond) pad(d1B.ctdcond) pad(d2C.ctdcond) pad(d3D.ctdcond) ...
    pad(d4E.ctdcond) pad(d5F.ctdcond) pad(d6G.ctdcond) pad(d7H.ctdcond) ...
    pad(d7I.ctdcond) pad(d8J.ctdcond)];
ctdtemp = [pad(d1A.ctdtemp) pad(d1B.ctdtemp) pad(d2C.ctdtemp) pad(d3D.ctdtemp) ...
    pad(d4E.ctdtemp) pad(d5F.ctdtemp) pad(d6G.ctdtemp) pad(d7H.ctdtemp) ...
    pad(d7I.ctdtemp) pad(d8J.ctdtemp)];
ctdsal = [pad(d1A.ctdsal) pad(d1B.ctdsal) pad(d2C.ctdsal) pad(d3D.ctdsal) ...
    pad(d4E.ctdsal) pad(d5F.ctdsal) pad(d6G.ctdsal) pad(d7H.ctdsal) ...
    pad(d7I.ctdsal) pad(d8J.ctdsal)];
ctdsigma = [pad(d1A.ctdsigma) pad(d1B.ctdsigma) pad(d2C.ctdsigma) pad(d3D.ctdsigma) ...
    pad(d4E.ctdsigma) pad(d5F.ctdsigma) pad(d6G.ctdsigma) pad(d7H.ctdsigma) ...
    pad(d7I.ctdsigma) pad(d8J.ctdsigma)];
ctdvelprof = [pad(d1A.ctdvelprof) pad(d1B.ctdvelprof) pad(d2C.ctdvelprof) pad(d3D.ctdvelprof) ...
    pad(d4E.ctdvelprof) pad(d5F.ctdvelprof) pad(d6G.ctdvelprof) pad(d7H.ctdvelprof) ...
    pad(d7I.ctdvelprof) pad(d8J.ctdvelprof)];

%% Concatenate QC flags
ctdseapres_qc = [pad_qc(d1A.ctdseapres_qc) pad_qc(d1B.ctdseapres_qc) pad_qc(d2C.ctdseapres_qc) ...
    pad_qc(d3D.ctdseapres_qc) pad_qc(d4E.ctdseapres_qc) pad_qc(d5F.ctdseapres_qc) ...
    pad_qc(d6G.ctdseapres_qc) pad_qc(d7H.ctdseapres_qc) pad_qc(d7I.ctdseapres_qc) pad_qc(d8J.ctdseapres_qc)];
ctdtemp_qc = [pad_qc(d1A.ctdtemp_qc) pad_qc(d1B.ctdtemp_qc) pad_qc(d2C.ctdtemp_qc) ...
    pad_qc(d3D.ctdtemp_qc) pad_qc(d4E.ctdtemp_qc) pad_qc(d5F.ctdtemp_qc) ...
    pad_qc(d6G.ctdtemp_qc) pad_qc(d7H.ctdtemp_qc) pad_qc(d7I.ctdtemp_qc) pad_qc(d8J.ctdtemp_qc)];
ctdcond_qc = [pad_qc(d1A.ctdcond_qc) pad_qc(d1B.ctdcond_qc) pad_qc(d2C.ctdcond_qc) ...
    pad_qc(d3D.ctdcond_qc) pad_qc(d4E.ctdcond_qc) pad_qc(d5F.ctdcond_qc) ...
    pad_qc(d6G.ctdcond_qc) pad_qc(d7H.ctdcond_qc) pad_qc(d7I.ctdcond_qc) pad_qc(d8J.ctdcond_qc)];
ctdsal_qc = [pad_qc(d1A.ctdsal_qc) pad_qc(d1B.ctdsal_qc) pad_qc(d2C.ctdsal_qc) ...
    pad_qc(d3D.ctdsal_qc) pad_qc(d4E.ctdsal_qc) pad_qc(d5F.ctdsal_qc) ...
    pad_qc(d6G.ctdsal_qc) pad_qc(d7H.ctdsal_qc) pad_qc(d7I.ctdsal_qc) pad_qc(d8J.ctdsal_qc)];
ctdsigma_qc = [pad_qc(d1A.ctdsigma_qc) pad_qc(d1B.ctdsigma_qc) pad_qc(d2C.ctdsigma_qc) ...
    pad_qc(d3D.ctdsigma_qc) pad_qc(d4E.ctdsigma_qc) pad_qc(d5F.ctdsigma_qc) ...
    pad_qc(d6G.ctdsigma_qc) pad_qc(d7H.ctdsigma_qc) pad_qc(d7I.ctdsigma_qc) pad_qc(d8J.ctdsigma_qc)];

%% Concatenate soak info
soak_duration_s = [d1A.soak_duration_s d1B.soak_duration_s d2C.soak_duration_s ...
    d3D.soak_duration_s d4E.soak_duration_s d5F.soak_duration_s d6G.soak_duration_s ...
    d7H.soak_duration_s d7I.soak_duration_s d8J.soak_duration_s ...
    ];
soak_depth_dbar = [d1A.soak_depth_dbar d1B.soak_depth_dbar d2C.soak_depth_dbar ...
    d3D.soak_depth_dbar d4E.soak_depth_dbar d5F.soak_depth_dbar d6G.soak_depth_dbar ...
    d7H.soak_depth_dbar d7I.soak_depth_dbar d8J.soak_depth_dbar ...
    ];
soak_n_filtered = [d1A.soak_n_filtered d1B.soak_n_filtered d2C.soak_n_filtered ...
    d3D.soak_n_filtered d4E.soak_n_filtered d5F.soak_n_filtered d6G.soak_n_filtered ...
    d7H.soak_n_filtered d7I.soak_n_filtered d8J.soak_n_filtered ...
    ];

%% Save
outfile = [fans_path 'PROC_CTD_FANS_oceanCasts.mat'];
save(outfile, ...
    'ctddate', 'ctdid', 'ctdlat', 'ctdlon', 'ctddepth_mean', 'ctdseapres', 'ctdsampltime', ...
    'ctddepth', 'ctdcond', 'ctdtemp', 'ctdsal', 'ctdsigma', 'ctdvelprof', ...
    'ctdseapres_qc', 'ctdtemp_qc', 'ctdcond_qc', 'ctdsal_qc', 'ctdsigma_qc', ...
    'soak_duration_s', 'soak_depth_dbar', 'soak_n_filtered', ...
    'atmhPa1', 'atmhPa2', 'atmwindspeed', 'atmwinddirection', 'atmrelativehumidity');

disp(' ')
disp('════════════════════════════════════════════════════════════════')
disp('  CONCATENATION COMPLETE - VERSION 5')
disp('════════════════════════════════════════════════════════════════')
fprintf('  File saved: %s\n', outfile)
fprintf('  Total profiles: %d\n', length(ctdid))
disp(' ')
disp('  Stations included:')
for i = 1:length(stn_summary)
    fprintf('    - %s (%d profile%s)\n', stn_summary(i).name, stn_summary(i).n, ...
        repmat('s', 1, stn_summary(i).n > 1));
end
disp(' ')
disp('  Variables included:')
disp('    - CTD data: ctdtemp, ctdsal, ctdcond, ctdsigma, ctdvelprof')
disp('    - QC flags: ctdtemp_qc, ctdsal_qc, ctdcond_qc, ctdsigma_qc, ctdseapres_qc')
disp('    - Soak info: soak_duration_s, soak_depth_dbar, soak_n_filtered')
disp('    - Validation: validation_decisions, validation_all (per station)')
disp('    - QC summary: qc_summary_all (per station)')
disp('    - Atmosphere: atmhPa1, atmhPa2, atmwindspeed, atmwinddirection, atmrelativehumidity')
disp('════════════════════════════════════════════════════════════════')
